### PR TITLE
Update to Piwigo 2.9.3

### PR DESCRIPTION
**Pull request by TheBlackReverand**
Please, when you push the new docker image, can you add additional tag?

Something like 2.9.3_b1 (piwigo 2.9.3 build 1)

That can help some people for container upgrade management.

Thanks

### CODE REVIEW

**Comment by mathieuruellan** [comment]
Hello,
Thank you for you PR.
Could you edit the README and the change history?

I will set addtionnal tags.

**Comment by TheBlackReverand** [comment]
README.md is up-to-date :+1:

**Review by mathieuruellan — APPROVED** [review]

**Comment by mathieuruellan** [comment]
It's in the queue.
the tag will be release-2.9.3

**Comment by TheBlackReverand** [comment]
Thanks

**Pull request merged**
