### PR TITLE
Update to Piwigo 2.8.5

### PR DESCRIPTION
**Pull request by maakuth**

### CODE REVIEW

**Comment by dsteinkopf** [comment]
Why isn't this accepted? There currently even is a 2.8.6 and a 2.9.0

**Comment by dsteinkopf** [comment]
I've just create a fork on github an docker hub: https://hub.docker.com/r/dsteinkopf/piwigo/
This fork will only exist until this repo here is updated again - not a "real" fork.

**Comment by mathieuruellan** [comment]
Hello, sorry, i didn't upgrade because i'm  busy. This piwigo docker version was for my personnal usage. 
I can upgrade, but i have to test migration. 
I'm not against that someone maintains seriously a piwigo docker, with another github and droping this repository.

kind regards.

**Comment by mathieuruellan** [comment]
Well it works well with 2..9. i will update that! Thank you

**Pull request closed without merging**
